version: "3.7"
services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"

  back:
    depends_on:
      - "db"
    build: "./backend"
    ports:
      - "3000:3000"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: sample
      DB_PORT: 3306
      DB_HOST: db
      RAILS_ENV: production
      RAILS_MAX_THREADS: 5
    volumes:
      - ".:/app"
      - "./config/docker/database.yml:/app/config/database.yml"

  front:
    stdin_open: true
    tty: true
    depends_on:
      - "back"
    build: "./frontend"
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
    volumes:
      - ".:/app"
      - "/app/frontend/node_modules"

volumes:
 db:
